// /// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Oreofe {
  Oreofe._();

  static const _kFontFam = 'AppIcons';
  // static const String? _kFontPkg = null;
  static const _kFontPkg = "AppIcons";

  static const IconData nav_community =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_discover =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_donation =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_user =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_home =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
