name: Build and Test

on: [push]
jobs: 
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Flutter
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Install dependencies 
      run: flutter pub get
    - name: Analyze Dart code
      run: flutter analyze -v
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
